# Generated by Django 3.1.2 on 2021-08-14 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210813_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finch',
            name='img',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='finch',
            name='name',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
